### ISSUE TITLE
Improve health checks for bouncer

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#113]
Currently the health check we use to ensure that the bouncer is working properly are very basic and they could be improved.

As highlighted in https://github.com/TheTorProject/ooni-sysadmin/pull/108
> The check for the bouncer being up I ended up reverting it to a much simpler one, because I couldn't figure out how to get the regexps to work

This ticket is about figuring out how to get prometheus regexps to work to validate that the bouncer response is in fact correct.

**Comment by SuperQ** [comment]
Any interest in adding non-blackbox monitoring? :smile: Checks like this are always going to be error-prone. Getting more direct instrumentation would be more reliable as you can get metrics on every function in the bouncer. Even adding [nginx-module-vts](https://github.com/vozlt/nginx-module-vts) would be useful to find out how many requests are being served.

**Comment by hellais** [comment]
@SuperQ yeah in the long term I think we want to have our services speak prometheus and publish more application specific metrics.

For example I have been rewriting the collector component in golang and are using there github.com/zsais/go-gin-prometheus to publish the number of submitted measurements by country and by platform: https://github.com/ooni/collector/blob/mvp-kiss/collector/metrics.go.

The nginx module is a good one and I think we should look into that, but I think the ideal scenario is that the metrics are published using some prometheus library by the application itself. Is this correct?

**Comment by SuperQ** [comment]
Yes, it's best to have the code itself do the tracking. It's pretty easy to use the official Go and Python libraries.

That's a very strange wrapper, wouldn't it be easier to use the Prometheus [client_golang](https://github.com/prometheus/client_golang) directly?

The nginx module idea helps because it lets you know what's going on inside nginx as well.

**Comment by hellais** [comment]
> That's a very strange wrapper, wouldn't it be easier to use the Prometheus [client_golang](https://github.com/prometheus/client_golang) directly?

go-gin-prometheus is basically just exposing client_golang as a gin middleware (which is the routing library we use in OONI golang tooling). The nice thing is that they already figured out how to log the request size, request duration and request count for gin, so we don't have to re-implement this ourselves.
It effectively though is still reliant most on the client_golang to expose the metrics: https://github.com/zsais/go-gin-prometheus/blob/master/middleware.go#L78.
