### ISSUE TITLE
Update node-irc under slack-irc-bridge

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#115]
Used docker container seems to have old `node-irc` module that has a bug disrespecting `messageSplit` that was fixed in martynsmith/node-irc#385.

It leads to messages truncated in the middle of word & loosing ~20 symbols while relaying large message from slack to IRC. That's quite annoying :(

Also, Slack bot messages likely do not propagate to IRC anymore, see [hellais fork](https://github.com/ekmartin/slack-irc/compare/master...hellais:feature/bot-notifications) for the feature.

- [ ] messageSplit
- [x] ~~Slack bot -> IRC (for monitoring)~~ (2018-08-30: we don't rely on IRC logs of #ooni-bots anymore)

**Comment by hellais** [comment]
Another neat feature to add to the slack bot, is maybe the ability to relay messages using a custom nick depending on the users slack handle.

I believe it's possible to send messages to an IRC channel without joining it, but I am not sure if you can set the nick without issuing a `/nick` command. If it is possible we could support sending `/msg` to the `#ooni-` channels with the name `$USERNAME-slack`, making the IRC usability a bit better.

**Comment by darkk** [comment]
>  I am not sure if you can set the nick without issuing a /nick command

AFAIK, you can't. Outgoing `PRIVMSG` has no nickname. 

I use weechat with gateway_rename.scm plugin and `plugins.var.guile.gateway_rename.gateways = "(OFTC * slacktopus <NICK>)` setting, it works for me, but it's not a generic solution.

**Comment by hellais** [comment]
This is done
