### ISSUE TITLE
slackin: down for two days

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#117]
Impact: slackin was unavailable for users to join community meeting

Detection: alert from @agrabeli_

Timeline UTC:
29 May 20:40 commit d4de11b839d818f76738229ceaf5f589cc770481 with typo
16 Jun 14:19 previous commit becomes commit 2c6f6231d3c5b7e7a2168575746b5bb086a8f7c1 after merging #89 and rewriting history
24 Jun 21:01 @darkk reverts `master` and opens PR #114 because of syntax error in vaulted yaml
25 Jun 20:10 nginx fails to start with ` [emerg] 122#122: invalid port in upstream "slackin:3000'" in /etc/nginx/conf.d/slack.openobservatory.org.ssl.conf:18` in https-portal container at slack.openobservatory.org
27 Jun 12:20 @agrabeli_ alerts @darkk on slackin being down
27 Jun 12:37 slackin is back up after 47895aeee77b0138c61b729bd07c3e585bfd697e

What went well:
- @agrabeli_ checked that slackin works a couple of days **before** community meeting
- it was easy to fix slack.openobservatory.org as deployment recipe was already there

What went wrong:
- rewritten history for production infrastructure updates
- broken `master` for a week
- @darkk assumed that the root cause is not typo but yet another docker DNS bug

What could be done to prevent relapse and decrease impact:
- [x] alerting of TLS certificate freshness (reason for #89)
- [x] alerting for slackin and slack-irc services
- [x] local pre-commit git-hook that checks basic syntax of ansible playbooks

**Comment by darkk** [comment]
Kind of relapse. `steveltn/https-portal:1.0.0` went wrong once again and did not update letsencrypt cert.
- [ ] get rid of `steveltn/https-portal`

**Comment by darkk** [comment]
TLS certificate freshness is monitored with `SSLCertExpires` alert.
Slack-IRC gateway liveness &mdash; b30e0d29d0512b8e1ce3cf1bd502388132c5af94
Syntax of ansible playbooks is checked with Travis &mdash; 9b48318dd8029f39b5fb834ce7b8147ec9b8172c

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
