### ISSUE TITLE
bouncer: 35min down after maintenance reboot

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#118]
Impact: bouncer was down for 35 minutes. Does it cause measurement loss for any ooniprobe versions? What sort of issues?

Timeline UTC:
13 Jun 10:53 [FIRING] Instance https://bouncer.ooni.io/bouncer down
13 Jun 11:02 @darkk pings @anadahz with basic diagnostics
13 Jun 11:20 @anadahz brings news from kargig that VM reboot was caused by maintenance
13 Jun 11:23 @hellais **(?)** starts dockerd at bouncer
13 Jun 11:28 [RESOLVED] Instance https://bouncer.ooni.io/bouncer down

What went well:
- alerting was prompt and relevant!

What went wrong:
- @darkk waited for ~10 minutes till it was obvious that alert message is not network flap
- four different people were bringing the service back

What could be done to prevent relapse and decrease impact:
- [ ] bouncer was not reboot-proof
- [x] there was no email notification to team@ regarding pending maintenance, it was impossible to switchover
- [ ] bouncer.ooni.io is SPOF and it has no automatic failover
- [ ] bouncer deployment recipe was "too meta" for @darkk to understand it during the incident

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
