### ISSUE TITLE
Use the naming convention suggested by @joelanders

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#13]
I noticed @joelanders decided to use the naming convention of using `-` instead of `_` I must say I don't have a strong opinion, but I just care about consistency.

So either one we pick it should be changed across the repo.

**Comment by anadahz** [comment]
@hellais @joelanders so whic naming convention are we using at the end?

**Comment by hellais** [comment]
Let's use `_` as that is the convention that seems to be part of ansible (like `group_vars`).

**Comment by joelanders** [comment]
+1 4 _

**Comment by anadahz** [comment]
Yay for underscore!

**Comment by hellais** [comment]
Perhaps we can close this once the naming has been made homogenous though?

**Comment by anadahz** [comment]
You are right reopened.

**Comment by hellais** [comment]
Is this done? What is missing to be done?

**Comment by hellais** [comment]
Any updates on this?

**Comment by darkk** [comment]
I'd say it depends on #94 :)

**Comment by darkk** [comment]
I feel like it also partly happened during #217. Remaining inconsistencies look consistent to me (`_` is used when ${entity} has `_` as part of name).
