### ISSUE TITLE
explorer was half-broken for 16 hours

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#138]
Impact: some users accessing explorer web-interface could not load `/scripts/vendor.js`, so web UI was broken for them

Detection: alert from user

Timeline UTC:
11 Aug 15:22...15:37: @darkk rolls out `node_exporter` with `nginx-prometheus` to `all:!no_passwd`
11 Aug 15:37 first `[crit] 13064#0: *1471 open() "/var/lib/nginx/proxy/7/00/0000000007" failed (13: Permission denied) while reading upstream ...` record in /var/log/nginx/error.log, NB: this error shows NO anomalies in access.log
12 Aug 02:18: dcf1 reports that _explorer is not rendering_, followed in 15 minutes by _Suddenly started working again_
12 Aug 07:30: @hellais confirms: _Chrome gives a `ERR_INCOMPLETE_CHUNKED_ENCODING` error when loading `https://explorer.ooni.torproject.org/scripts/vendor.js`_
12 Aug 07:46: @darkk applies `sudo chown -R www-data /var/lib/nginx/` to explorer
12 Aug 07:46: last `[crit] 13066#0: *20326 open() "/var/lib/nginx/proxy/3/34/0000000343" failed (13: Permission denied)` log line
12 Aug 08:08: @darkk applies chown to other _possibly_ affected hosts (`all:!no_nodeexp` having two nginx master processes running). These services seem to face NO real issues as there are no corresponding records in nginx/error.log. These hosts are:
- slack.openobservatory.org
- munin.ooni.io
- explorer.ooni.io
- get.ooni.io
- measurements.ooni.io
- notify.proteus.test.ooni.io
- prometheus.infra.ooni.io
- measurements-beta.ooni.io
- ooni-zoo.infra.ooni.io

13 Aug 14:20: incident published

What went well:
- @hellais re-checked user's report even after _up again_

What went wrong:
- darkk adjusted separate nginx installation to avoid conflicts with global logrotate, but have forgotten about other global nginx objects like temporary directories

What is still unclear:
- [ ] should we serve static files via nginx/cache instead of fetching them from application?
- [ ] will some sort of [exception tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/exceptions) catch that?
- is Domain Reliability AKA [Network Error Logging](https://www.chromestatus.com/feature/5391249376804864) already adopted by browsers? Seems, it's not: [WICG](http://wicg.github.io/network-error-logging/), [W3C](https://www.w3.org/TR/network-error-logging/), but I may be missing something.

What could be done to prevent relapse and decrease impact:
- [x] create separate temporary directories for nginx-prometheus
- [ ] start nginx-prometheus as unprivileged user instead of default _start-as-root_ mode
- [ ] setup alerting based on `error.log`, e.g. using google/mtail exporter or fstab/grok_exporter or something based on export of the log via syslog interface

**Comment by bassosimone** [comment]
> should we serve static files via nginx/cache instead of fetching them from application?

In principle, I'd say yes, as this would probably reduce the load induced by serving static assets, but:

Would this make deployment more complicated? That is, would it imply that we need to deploy static files in a VM and app files in another VM?

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
