### ISSUE TITLE
Cleanup orchestration deployment

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#145]
Cleanup after #112:
- [ ] `apt_key` using fingerprint instead of url
- [ ] `apt_repository` using `jessie` instead of `stable` (for yarn)
- [ ] cleanup proteus-db SQL scripts (they were one-shot)
- [ ] different postgresql users for different micro-services
- [ ] CA for postgres `sslmode=require`
- [ ] usage of SHA256SUMS to avoid re-downloading the binary to deploy configuration change, depends on TheTorProject/proteus#22
- [ ] cleanup variables with same name defined in different roles (e.g. `proteus_user`)
- [ ] cleanup handlers with same name defined in different roles (e.g. `restart proteus`)
- [ ] cleanup variables like `proteus_***_testing` splitting them into separate group
- [ ] determine the destiny of `notification_backend: proteus`, it's disabled, but is it dead code?
- [x] expose gorush metrics

**Comment by hellais** [comment]
This has been done as part of oonification.
