### ISSUE TITLE
Cleanup grav CMS deployment

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#150]
After #126:
- [ ] **fatal**: various configuration & data changes are dropped on re-deployment of the playbook -- check if `users` was the only affected entity
- [ ] grav is system of record, so it should have proper backups with freshness monitoring
- [ ] `/srv/grav` should be mostly root-owned
- [ ] cover everything with SSO cookie and expose public part explicitly
- [ ] download source files with checksum
- [ ] it's unclear if pgp5-fpm process should have www-data gid to listen on socket.
- [ ] monitor `/ping` page
- [ ] check if our php.ini is `php.ini-production` or `php.ini-development` :)

**Comment by hellais** [comment]
This machine has been zapped.
