### ISSUE TITLE
disk overflow at hkgmetadb

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#156]
Impact: airflow pipeline was stopped for two days due to unexpected disk shortage

Detection: (almost late) trend alert on disk usage

Timeline UTC:
30 Aug 00:40: 10% free at hkgmetadb.infra.ooni.io
04 Sep 14:40: backfill of failed buckets started through airflow pipeline
04 Sep 17:24: 48h-based disk overflow estimate triggers alert
04 Sep 17:33: 5% free
04 Sep 17:45: pipeline DAG is paused, running tasks continue running
04 Sep 18:10: 4Gb free (2.5%) at hkgmetadb.infra.ooni.io, vacuum cleans up some space
05 Sep 20:30: hkgmetadb shut down to move storage to LVM
05 Sep 22:30: hkgmetadb back up, pipeline DAG is unpaused
06 Sep 10:40: incident published

What went well:
- almost late alert is better than no alert
- GH allows to re-deploy another OS on the VM saving IP address while attaching old disk image as a separate device, that eases migration
- GH kernel supports LVM2, that allows to create disks of significant size: 9 slots for virtual disks with 100 Gb limit on new image. There is 200 GB limit for rootfs image that may be converted into ordinary image :)

What went wrong:
- lack of preventive alerts on momentary usage values made it rather nervous

What could be done to prevent relapse and decrease impact:
- [x] momentary alerts on inodes (50% warn, 75% crit) and size (80% warn, 90% crit, following dmeventd)
- [ ] estimate what other hosts may require moving to expandable disk storage
- [x] learn how to silence temporary irrelevant alerts in alertmanager 

TODO:
- [ ] drop oldroot at 2017-09-25

Interesting takeaways:
- [x] nginx-prometheus reads `/srv/ngxprom/scraper.htpasswd` on every request, absent file (due to `/srv` re-mounting) causes request failure, it may also explain issues during #155 
- [ ] nginx can start daemon without any listening ports defined (e.g. all sites-enabled deleted)
- [x] dockerized database may me shut down improperly. Probably "important" DBs should be moved out of docker containers because of that unless there is reason to keep them there... That's to be decided.
- non-root user for docker container processes makes it easy to understand if there are any files produced that should be preserved during migration

**Comment by darkk** [comment]
<details>
  <summary>docker logs pl-psql</summary>

```
darkk@hkgmetadb:~$ sudo docker logs --timestamps  pl-psql
2017-09-05T22:17:24.676950177Z LOG:  database system was interrupted; last known up at 2017-09-04 20:05:21 UTC
2017-09-05T22:17:24.715885659Z LOG:  database system was not properly shut down; automatic recovery in progress
2017-09-05T22:17:24.745406720Z LOG:  invalid record length at 31/E3109C28: wanted 24, got 0
2017-09-05T22:17:24.745430743Z LOG:  redo is not required
2017-09-05T22:17:24.823807878Z LOG:  MultiXact member wraparound protections are now enabled
2017-09-05T22:17:24.830726526Z LOG:  autovacuum launcher started
2017-09-05T22:17:24.831254936Z LOG:  database system is ready to accept connections
2017-09-05T22:18:51.115222819Z LOG:  received smart shutdown request
2017-09-05T22:18:51.115262788Z LOG:  autovacuum launcher shutting down
2017-09-05T22:18:51.122081957Z LOG:  shutting down
2017-09-05T22:18:51.207962728Z LOG:  database system is shut down
2017-09-05T22:25:19.794170930Z LOG:  database system was shut down at 2017-09-05 22:18:51 UTC
2017-09-05T22:25:19.820505776Z LOG:  MultiXact member wraparound protections are now enabled
2017-09-05T22:25:19.848480404Z LOG:  autovacuum launcher started
2017-09-05T22:25:19.849366915Z LOG:  database system is ready to accept connections
```
</details>

<details>
  <summary>DR plan</summary>

+ docker stop pl-psql
+ $ sudo docker logs --timestamps --since 10m pl-psql
+ poweroff machine
+ create 10G image for dom0
+ add two 100Gb chunks
+ deploy new OS
+ attach oldroot image to xvdd (second)
+ copy SSH keys
+ mount old root read-only(!)
+ restart SSH
+ apply dom0
+ disable firewall rule
+ apt-get install lvm2 rsync xfsprogs
+ $ pvcreate /dev/xvdb1 && pvcreate /dev/xvdc1
+ $ vgcreate hkgmetadb /dev/xvdb1 /dev/xvdc1
+ $ lvcreate --name srv -l 100%VG hkgmetadb
+ $ mkfs.xfs -L hkgmetadbsrv /dev/hkgmetadb/srv
+ stop nginx-prometheus and node_exporter, move stuff from old /srv to new /srv
+ __copy__ database
+ apply hkgmetadb ruleset
+ poweroff machine
+ detach root image
+ poweron machine
+ start docker container (if needed)
+ enabled firewall rule
</details>

There is also some xfs_info difference, it's unclear if `/srv` should be tuned to have same options as `rootfs`:
```
rootfs
projid32bit=0
log      =internal               bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=8 blks, lazy-count=1
mount options: +sunit=8192,+swidth=8192

/srv
projid32bit=1
log      =internal log           bsize=4096   blocks=25599, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
```

**Comment by bassosimone** [comment]
> nginx can start daemon without any listening ports defined (e.g. all sites-enabled deleted)

Out of curiosity: I guess `nginx` I/O loop is such that, even without anything to do (i.e. listening), it still runs. So, perhaps, it has some long-running internal task in the I/O loop?

Does `nginx` spawn a single process or more than one? Was/were the spawned process completely idle?

> non-root user for docker container processes makes it easy to understand if there are any files produced that should be preserved during migration

Interesting!

**Comment by darkk** [comment]
> nginx

All children were spawned and all the processes are quite idle.

> Interesting!

root can write anywhere, non-root can't change uid of it's own files, so these files may be found with simple `find` :)

**Comment by darkk** [comment]
> dockerized database may me shut down improperly

See #172 and c58935fb02cd151e75f86de6a01fe18869d8fb5b, other DBs are not running under docker.

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
