### ISSUE TITLE
DNS issues at HKG cause pipieline failure

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#159]
Impact: bucket was processed by the pipeline 3.5 days late

Detection: occasional detection at airflow dashboard

Timeline UTC, 2017-09-07:
07 Sep 00:01 reports_raw_s3_ls ... s3.amazonaws.com ... [Errno -3] Temporary failure in name resolution
07 Sep 00:23: gaierror: [Errno -2] Name or service not known
07 Sep 00:28: meta_pg, psycopg2.OperationalError: could not translate host name "hkgmetadb.infra.ooni.io"
10 Sep 14:30: bucket re-processed

What went well:
- airflow indicates failure in logs, that's quite easy to re-process failed bucket
- both nameservers were tried two times (default `attempts:2`) with 1s timeout (configured `timeout:1`), at least mail sending code works like that and fails after 4s
- there is no indication of network failure, AMS prometheus instance was collecting metrics without interruption 

What went wrong:
- airflow could not send alert email to remote SMTP server because of failing DNS :-)

What is still unclear:
- why were some resolving attempts failing with _Temporary failure in name resolution_ while another (SMTP client) was failing with _Name or service not known_? Failures were consistent, same FQDN failed same way on retries.
- [ ] is it [OpenDNS](http://system.opendns.com/) to blame? HKG VMs use OpenDNS in resolv.conf. As far as I see, there are no incidents reported. Should we have another "open resolver" as a fallback, e.g. [Verisign Public DNS](https://www.verisign.com/security-services/public-dns/index.xhtml) who are trying hard to say "we don't sell your data" or [another](https://www.lifewire.com/free-and-public-dns-servers-2626062)?
- [x] should we use AMS GH DNS as a fallback?
- [x] should we setup small VM acting as local DNS recursor in HKG to be used as a fallback?
- [x] does it make sense to have local SMTP relay?
- [x] does it make sense to have local SMTP queue, e.g. postfix sending via Amazon SES as a smarthost?
- [x] does it make sense to alert on pipeline task status via pushgateway?

**Comment by darkk** [comment]
AMS GH DNS for HKG is insane idea: RTT is ~275ms. Adding `1.0.0.1` to OpenDNS sounds reasonable to me.

WRT SMTP &mdash; alerts are sent directly to MX since 2d220b23dcb7c7e07abd3e6103a8922a52d2fed4. Failures to send alerts are accounted within alertmanager. Alertmanager cross-monitoring  is part of #189

**Comment by darkk** [comment]
Pipeline task status is monitored since #206  (e.g. 3f7cfac024bc8accbfcdcd314e8b952742215e75)

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
