### ISSUE TITLE
chameleon pipeline down for three days

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#162]
Impact: pipeline processing was delayed for three days

Detection: alert from airflow

Timeline UTC:
09 Sep 05:18: chameleon reboots (just 40 minutes after pipeline is done)
09 Sep 18:11: chameleon reboots once again
10 Sep 02:12: luigi_pipeline fails to create sanitised bucket, s3 and datacollector uploads fail as well
11 Sep 16:50: @darkk notices that chameleon pipeline fails as airflow pipeline can't run dependent tasks
12 Sep 16:55: @darkk launches ooni-pipeline-luigid.service and starts backfill
12 Sep 17:30: incident published

What went well:
- airflow had explicit dependency on luigi pipeline success

What went wrong:
- shared hardware was rebooted without announcement
- chameleon services were not reboot-proof

What could be done to prevent relapse and decrease impact:
- [ ] make services reboot-proof

**Comment by darkk** [comment]
Probably, most of the services are reboot-proof now, but I'd suggest to run a round of kernel upgrades & reboots to ensure.

**Comment by hellais** [comment]
> Probably, most of the services are reboot-proof now, but I'd suggest to run a round of kernel upgrades & reboots to ensure

This is going to happen as part of: https://github.com/ooni/backend/issues/265


Closing this in light of: https://github.com/ooni/backend/issues/343
