### ISSUE TITLE
OONI backend services running low on disk space

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#166]
Impact: None 

Detection: Alert from prometheus

Timeline UTC:
~24 Sep 07:03: [FIRING] Disk usage at b.web-connectivity.th.ooni.io:9100 over 80%
27 Sep 10:10: @hellais logs into `b.web-connectivity.th.ooni.io` and runs `rm -rf /data/b.web-connectivity.th.ooni.io/var/log/ooni/oonibackend.log.*` deleting 7GB of logs.
27 Sep 10:13: [RESOLVED] Disk usage at b.web-connectivity.th.ooni.io:9100 over 80%

What went well:

* Alerting was good

What went wrong:

* Logs are not getting rotated

What we should do to fix it:

* [ ] Logs should be rotated on ooni-backend machines

**Comment by darkk** [comment]
17 Nov, same story at `b.web-connectivity.th.ooni.io`.
I compressed the logs to `/data/c.web-connectivity.th.ooni.io_var_log_ooni` stash instead of deleting.

**Comment by darkk** [comment]
04 Oct 00:11, same story at `b.web-connectivity.th.ooni.io`
04 Oct 11:16, resolved (logs compressed)

Probably, we should define some number of days to store logs and codify it as a part of data policy?

**Comment by hellais** [comment]
The plan for dealing with logs is documented in this epic: https://github.com/ooni/backend/issues/259

Closing this in light of: https://github.com/ooni/backend/issues/343
