### ISSUE TITLE
test.ooni.io AKA ooni-zoo can't properly renew certificates

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#168]
Impact: various test services go down for a while

Detection: alert from prometheus

Timeline UTC, 28 Sep:
00:00:01 ooni-zoo systemd[1]: Starting Certbot...
00:00:01 ooni-zoo CRON[11480]: (root) CMD (certbot  certonly...
00:00:01 ooni-zoo CRON[11483]: (root) CMD (certbot certonly...
00:00:03 oonibackend.log `Main loop terminated.`
00:00:03 docker logs `Starting TCP DNS Helper on 57004`
00:51:53 ooni-zoo certbot[19022]: Attempting to renew cert from /etc/letsencrypt/renewal/test.ooni.io.conf produced an unexpected error: At least one of the required ports is already taken..
00:52:03 oonibackend.log `[twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 16.4.1 (/usr/bin/python 2.7.9) starting up.`

What went well:
- collision of several certbot instances self-healed the test instance of the service

What went wrong:
- previous incident was not documented in tracker

> 2017-07-29 16:11:53 darkk> @hellais: FYI, https cert at test.ooni.io was not autoupdated due to SEEMINGLY misbehaving detector of bound port in certbot. That's still to be investigated, but I assume that it's confused by several IP addresses at that box.

What could be done to prevent relapse and decrease impact:
- [ ] try updating certbot and check if it handles the box with several IP addresses properly
- [ ] drop ooni-zoo with "unusual" network configuration

**Comment by bassosimone** [comment]
> drop ooni-zoo with "unusual" network configuration
totally

**Comment by hellais** [comment]
I edited in the meantime `/etc/cron.d/letsencrypt_renew_certs-6e9defa0-4c76-5a39-be41-73baa7b23d78` to include stopping of both docker containers before attempting to renew it:

```
-@daily root certbot certonly --standalone  --preferred-challenges http-01 --noninteractive --text --agree-tos --email admin@openobservatory.org --domains stage.ooni.io,bouncer.stage.ooni.io,a.collector.stage.ooni.io,a.web-connectivity.th.stage.ooni.io --pre-hook "docker stop ooni-backend-staging-bouncer" --post-hook "cp /etc/letsencrypt/live/stage.ooni.io/privkey.pem /etc/letsencrypt/live/stage.ooni.io/fullchain.pem  /data/staging-bouncer/tls   && docker start ooni-backend-staging-bouncer"
+ @daily root certbot certonly --standalone  --preferred-challenges http-01 --noninteractive --text --agree-tos --email admin@openobservatory.org --domains stage.ooni.io,bouncer.stage.ooni.io,a.collector.stage.ooni.io,a.web-connectivity.th.stage.ooni.io --pre-hook "docker stop ooni-backend-staging-bouncer && docker stop ooni-backend-testing-bouncer" --post-hook "cp /etc/letsencrypt/live/stage.ooni.io/privkey.pem /etc/letsencrypt/live/stage.ooni.io/fullchain.pem  /data/staging-bouncer/tls   && docker start ooni-backend-staging-bouncer;docker start ooni-backend-testing-bouncer"
```

Side note:

There are currently 3 different cronjobs for renewing the certs (with `@daily` and `@monthly` regularity), none of which I think actually work properly (or even worked properly for that matter):

```
/etc/cron.d/letsencrypt_renew_certs-staging-bouncer
/etc/cron.d/letsencrypt_renew_certs-testing-bouncer
/etc/cron.d/letsencrypt_renew_certs-6e9defa0-4c76-5a39-be41-73baa7b23d78
```

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
