### ISSUE TITLE
hkgmetadb silently down for 1d18h

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#173]
Impact: pipeline was sending alerts, api.ooni.io was likely down

Detection: airflow alert

Timeline UTC:
05 Oct 19:46: `LOG:  database system is shut down`, to extend LVM volume (see also #172)
05 Oct 23:15: @darkk goes to LED to get to YUL
07 Oct 13:49: `LOG:  database system is ready to accept connections`

What went well:
- airflow was complaining about the issue daily

What could be done to prevent relapse and decrease impact:
- [ ] api.ooni.io end-to-end monitoring

**Comment by hellais** [comment]
end to end monitoring issue: https://github.com/ooni/explorer/issues/159

closing this in light of: https://github.com/ooni/backend/issues/343
