### ISSUE TITLE
Peering issues at $(dig -t A prometheus.infra.ooni.io)/24

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#174]
Impact: prometheus is unreachable from [significant number of ASes](https://atlas.ripe.net/measurements/9731384/?filter=&show_only=Failed#!map). Other OONI VMs are not affected (all of them are in different /24 networks), cross-DC communication within GH is OK.

Detection: accidental detection from AS5769

Timeline UTC:
09 Oct 02:27 `ssh: connect to host prometheus.infra.ooni.io port 22: Network is unreachable`
09 Oct 03:12 mailed to support@
12 Oct 10:44 support@ claims routing misconfiguration to be resolved, situation improved from [A](https://atlas.ripe.net/measurements/9733651/?filter=&show_only=10#!map) to [B](https://atlas.ripe.net/measurements/9737705/?filter=&show_only=10#!map), but there are some blackholes still out there (OTOH, the reason for those networks to block traffic is unclear)

What is still unclear:
- [x] what is the cause of peering issue? is it something we can deal with?
- [ ] do we want to monitor endpoint blackholing & reachability? See also case of [Torproject mirror cloud.ipnett.se having connectivity issues](https://trac.torproject.org/projects/tor/ticket/23325). E.g. `ping` via RIPE Atlas weekly.

See also [RIPE Atlas measurements to GH (AS47172)](https://atlas.ripe.net/measurements/?page=1&search=asn:47172#tab-ping).

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
