### ISSUE TITLE
Sanitised s3 reports have not been written for weeks

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#180]
Impact: `ooni-public` s3 bucket does not contain freshest data

Detection: somebody using the s3 bucket pinged @hellais 

Timeline UTC:
24 Oct 17:30: Somebody pings hellais about it
24 Oct 20:17: @hellais: @darkk do you know why s3 stopped being populated since 2017-10-02?
I guess that is due to legacy pipeline having stopped, but I thought the new pipeline also wrote json files to s3, is that not the case?
24 Oct 20:18: @hellais logs into aws account and checks that the `ooni-public` s3 files are not there. The `ooni-private` files are there though.
24 Oct 20:20: @hellais checks airflow graph logs.
24 Oct 20:21: @hellais It seems like s3 ls has been failing for many weeks.
@darkk maybe tomorrow we can look into this together and maybe point the new pipeline to the new s3 bucket as well
It looks like the aws ls command is failing:
```
[2017-10-24 00:00:21,485] {base_task_runner.py:95} INFO - Subtask: [2017-10-24 00:00:21,484] {bash_operator.py:94} INFO - subprocess.CalledProcessError: Command '['aws', 's3', 'ls', '--recursive', 's3://ooni-public/sanitised/2017-10-23']' returned non-zero exit status 1
```

What went well:

* airflow interface is super useful to debug and troubleshoot this sorts of issues

What could be done to prevent relapse and decrease impact:

* [x] re-enable notifications to admin@ or team@ about airflow errors and maybe post them to slack too
* [x] migrate sanitised reports to the `ooni-data` s3 public bucket (see: https://github.com/TheTorProject/ooni-sysadmin/issues/179)

**Comment by darkk** [comment]
xref: #176

**Comment by darkk** [comment]
Notifications are there, _sanitised_ data is to be dropped as a part of #283 
So, I'm closing the incident ticket as all the checkboxes got their tickmarks.
