### ISSUE TITLE
Rename measurements.ooni.io to api.ooni.io

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#188]
In order to complete this we should:

* [ ] Look at access.log to ensure nothing breaks
* [ ] Migrate api.ooni.io over to the same host as measurements.ooni.io
* [ ] Setup redirects from measurements.ooni.io -> api.ooni.io

We should probably also see if we should be adding a `robots.txt` to avoid search engines crawling all the raw measurement files.

cc @darkk

**Comment by darkk** [comment]
Happened in 9acb05a76b8b9f08162f5d176008fe3839ac55be
