### ISSUE TITLE
explorer down for ~ hour, prometheus down for ~ week

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#189]
Impact: TBD

Detection: alert from StatusCake and follow-up investigation

Timeline UTC:
12 Dec 16:44 StatusCake reports explorer to be down
12 Dec 16:55 ~ @darkk clicks a link from the alert, ensures that the website renders "somehow"
12 Dec 17:15 @hellais asks if explorer is down or just re-deployed
12 Dec 17:20 @darkk gives explorer DB (ssdams) some care and discovers queries stuck for 20min
12 Dec 17:27 StatusCake reports explorer to be up

All the affected queries are pagination queries with huge OFFSET and are shown below. Seems, either something like _late row lookup_ hack or using `sort_key >= X` is required. Also, it's trivial to reproduce the issue: go to [country page](https://explorer.ooni.torproject.org/country/US), go to page field, do a keyboard chord `123456` over the field: every pressed key triggers request that runs a query in the DB, alike behavior is observed with unfortunate mouse wheel scroll :-)
```
postgres=# SELECT query_start, query FROM pg_stat_activity where state != 'idle';
          query_start          |                                                                                   query                                                                                    
-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 2017-12-12 17:21:56.974043+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9134700
 2017-12-12 17:21:53.555126+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9134900
 2017-12-12 17:21:29.713349+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9134800
 2017-12-12 16:59:33.394532+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9135100
 2017-12-12 17:01:58.916602+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9135000
 2017-12-12 16:59:21.727253+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9135300
 2017-12-12 16:59:31.082398+00 | SELECT "test_name","input","probe_cc","test_start_time","report_id","probe_asn" FROM "public"."metrics" WHERE "probe_cc"=$1 ORDER BY "input" DESC LIMIT 100 OFFSET 9135200
 2017-12-12 17:24:57.76253+00  | SELECT query_start, query FROM pg_stat_activity where state != 'idle';
```

During investigation of performance characteristics of the incident it was accidentally noticed that Prometheus is also down for quite a long time:

04 Dec 22:30 ~ the earliest "alive" datapoint in Prometheus for several 
05 Dec 00:33 TCP connections count starts growing from 16
05 Dec 02:29 TCP connections stop growing at 1024, that's ~8.5 conns per 1min
![tcp connections and prometheus 2017-12-12 23-08-23](https://user-images.githubusercontent.com/21046/33905966-7b306ef4-df91-11e7-9549-1ef69fe3cc31.png)
05 Dec 02:32:54 `level=warning msg="Series quarantined."  ... reason="open /srv/prometheus/data/e7/ec2636fd82b2d1.db: too many open files"`
05 Dec 02:30 ~ the latest "alive" datapoint in Prometheus
12 Dec 16:00 ~ @darkk notices that there were no Prometheus alerts about SSL Cert expiration since ~ Dec 07 at `api.ooni.io` during `ooni-measurements` update
12 Dec 18:00 ~ @darkk notices that grafana does not load dashboards properly
12 Dec 18:19 @darkk restarted Prometheus because of 1024 open FDs

Prometheus v1.6 lives in AMS, all the nodes that had {80...120} connections opened towards them live in HKG, seems, all HKG nodes were affected, but the data was mostly successfully scraped, remaning graphs are there.

What went well:
- /var/log/syslog is stored for a week, but /var/log/daemon is stored for ~ month, that's handy as Prometheus logs there (via systemd, journalctl and others)
- SOME data was recovered

What went wrong:
- Prometheus had lost lots of data including quite ancient data, but that's v1.6 that is probably not "supported"
- We were blind for a week

What is still unclear:
- What was actually happening? I expect Prometheus to have scrape timeouts.
- [ ] can postgres properly implement late row lookup with LIMIT / OFFSET or is `sort_key > $1` required?

What could be done to prevent relapse and decrease impact:
- [ ] review existing pagination APIs and implementation
- [ ] update StatusCake to show better URL
- [ ] ensure that logs are stored for 15+ days (same retention policy as one for Prometheus)
- monitor monitoring from independent instance (cross monitoring of two instances)
  - [ ] define Prometheus vitals to alert upon and verify them using some data leftovers
  - [ ] watch log files for unusual records
  - [ ] check if altermanager actually alerts using daily alert to slack at, for example, St. Petersburg noon (to be co-incident with noon cannon) based no some `node_time` math for some node

**Comment by darkk** [comment]
To move Amazon out of email notification loop following IP addresses are added to @openobservatory.org [whitelist](https://support.google.com/a/answer/176600), these addresses should also be added to SPF and used to deliver messages directly to MX.

> brie.darkk.net.ru  has address 139.162.172.21                                                                                                       
> brie.darkk.net.ru  has IPv6 address 2a01:7e01::f03c:91ff:fe0a:f4eb                                                                                  
> prometheus.infra.ooni.io  has address 37.218.245.43

**Comment by SuperQ** [comment]
Prometheus does have scrape timeouts, default is 10 seconds.  Configurable at global and per-job.

One recommendation is to avoid long network links between Prometheus and targets.  But spin up a local Prometheus when possible for each isolated network.  The idea is that you don't want to implicitly monitor the network as well as the targets.

**Comment by darkk** [comment]
> Prometheus does have scrape timeouts

Yep, I know, but I failed to deduce from logs the root cause of socket leak. Do you want to look at the logs given the fact that it was still 1.6 and will be soon upgraded to 2.0? I doubt that it's useful, but maybe I'm wrong :-)

I agree that long network links leads to monitoring the network as well, but I consciously choose to have some false positives and gaps having single prometheus installation for ~50 VMs instead of three.

By the way, @SuperQ, is there some "rule of thumb" to monitor prometheus / altermanager liveness for low-volume installations? Is it just `/-/health` check?

**Comment by SuperQ** [comment]
As you add more targets, you'll probably need more FDs.  It needs one for every target atleast.  We ran into [the same problem](https://gitlab.com/gitlab-cookbooks/gitlab-prometheus/blob/master/templates/default/sv-prometheus-run.erb#L3). :cry: 

Usually we just alert on target `up` metrics[0].  You can also look at `scrape_samples_scraped` and `scrape_duration_seconds`.  

[0]: https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series

**Comment by darkk** [comment]
> As you add more targets

I understand that, but it's not the root cause of the case. The configuration was static during the incident. The graph in the post is just for 2-hour window.

> `scrape_samples_scraped`

Yep, it reveals something interesting. Probably, that's the story of bad network as well :-)

![screenshot-2017-12-18 prometheus time series collection and processing server 2](https://user-images.githubusercontent.com/21046/34119728-4e538b3a-e434-11e7-8caa-58730bb31181.png)

**Comment by hellais** [comment]
May be relevant to: https://github.com/ooni/backend/issues/243

Closing due to: https://github.com/ooni/backend/issues/343
