### ISSUE TITLE
measurements data was not readable for 2¼ hours

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#201]
Impact: measurements were not readable for 2¼ hours

Detection: alert from @agrabeli

Timeline UTC:
17 Jan 15:39 events.proteus.test.ooni.io went down
17 Jan 17:03 @darkk ensures that it's network issue (freshly created VM is also unreachable)
17 Jan 17:23 mail to support@ WRT events.proteus.test.ooni.io
18 Jan 11:03 events.proteus.test.ooni.io is back up
18 Jan 11:14 reply from support@ confirming that it was a network misconfiguration during Meltdown patching
18 Jan 14:57 datacollector.infra.ooni.io goes down 
18 Jan 15:25 @darkk assumes that it's same networking issue and mails to support@
18 Jan 16:55 @agrabeli notifies that the issue affects api.ooni.io as autoclaved files are fetched from datacollector
18 Jan 17:16 @darkk re-routes `api.ooni.io` to fetch autoclaved files from `s3://ooni-data`
18 Jan 21:18 support@ asks if the incident is resolved or not
18 Jan 21:21 @hellais and @darkk confirm that the incident is ongoing, ask if any issues with the network are observed or not
19 Jan 09:21 @darkk starts `root` pw reseting to get console access, the VM inconsisteltnly goes up and down. Probably, GH was also rebooting same VM / hardware.
19 Jan 09:58 support@ confirms that there are no visible networking issues 
19 Jan 10:22 @darkk fixes two conflicting iptables scripts (legacy and "modern"), VM is back to network
19 Jan 10:32 VM becomes green after `restart nginx-prometheus` as it failed due to `bind() to 37.218.240.67:9100 failed (99: Cannot assign requested address)`

What went wrong:
- wrong assumption that the lightning strikes twice :)
- VMs / services were unable to boot properly after reboot: there were two scripts creating `NFS` chain and there was a conflict between them

Also, some security issues in GH were accidentally discovered while resolving the issue.

What could be done to prevent relapse and decrease impact:
- `root` password, as mentioned in #196
- [ ] `/etc/network/interfaces` tuned as part of `fw` role
- [ ] kernel upgrades and controlled reboots
- [ ] bind to `*:port` instead of `IP:port` for non-loopback IPs
- [ ] automatic failover & hot standby for services (planned for 2019... :-/)

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
