### ISSUE TITLE
API was down for ~2h due to kernel NULL pointer dereference at tcp_push

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#210]
Impact: api.ooni.io was responding with nginx _gateway timeout_ error page for two hours

Detection: alert from @anadahz 

Timeline UTC:
05 Apr 13:22 @darkk reboots VM while deploying new version of API as soon as docker was unable to shutdown container properly (possibly, due to OOM), VM upgrades kernel from 4.14.12 to 4.14.30
05 Apr 16:31 first `BUG: unable to handle kernel NULL pointer dereference` message in dmesg, gunicorn worker gets stuck in `D` state
06 Apr 07:33 last `BUG: unable to handle kernel NULL pointer dereference` message
06 Apr 07:33:57 `[error] 3751#3751: *55127 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 66.249.70.9, server: api.ooni.io`
06 Apr 09:31 @anadahz reports _I can't load api.oo (504 Gateway Time-out_
06 Apr 09:42 up, @darkk rebooted VM as soon as kernel bug may lead to some inconsistent state in kernel.

It's not 100% clear, but it could be https://bugzilla.kernel.org/show_bug.cgi?id=199211

What could be done to prevent relapse and decrease impact:
- [ ] `BUG` and `Oops` log monitoring
- [ ] `D`-state process monitoring, `node_procs_blocked` does not account them, `kernel.hung_task_*` is not available in GH kernel as `CONFIG_DEBUG_KERNEL is not set` and `config DETECT_HUNG_TASK depends on DEBUG_KERNEL`

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
