### ISSUE TITLE
c.web-connectivity.th down for 17.5 hours

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#211]
Impact: c.web-connectivity.th was down for 17.5 hours

Detection: Prometheus alert

Timeline UTC:
28 Feb 00:05: `Possible SYN flooding` kernel message (probably, unrelated)
01 Mar 02:09: some request came and have taken ~all available memory. That was not enough to trigger OOM, but was trigger enough to put machine under memory pressure and swap the code out that leaded to lots of %iowait
01 Mar 02:22: node_exporter stopped responding, machine was still responding to pings and some requests were served according to logs
01 Mar 04:20 the last served requests (but given 3m to serve a request it's unlikely that test helpers client were getting it)
01 Mar 19:36: @darkk rebooted VM from GH control panel & it came back alive

What went wrong:
- OOMless OOM :-(
- alert message was lost for a while because of `BlackboxDown` [alarm fatigure](https://en.wikipedia.org/wiki/Alarm_fatigue)

What could be done to prevent relapse and decrease impact:
- [x] _decrease_ alert grouping for email to improve message chain grouping to make it more "dashboardish"
- [ ] use softdog at VMs that do not _store_ data and can be hard-rebooted ~ safely ?
- [x] alert on [swapping](https://dev.gitlab.org/cookbooks/runbooks/commit/013c7f37a49caaeda00b89248a3d259b8b770e1b#20caf10e8b0fafd85539e4ed5f68c2bef2d82dd3) ?

**Comment by SuperQ** [comment]
An alert on `rate(node_vmstat_pswpin[5m])` might be useful to detect nodes that are swap thrasing.  Note, swap out isn't really necessary, as it's mostly harmless, it's the swap in that's a big problem because it's data that shouldn't have been swapped out.

**Comment by darkk** [comment]
@SuperQ that works well when swap is actually enabled, otherwise `node_vmstat_pswpin` is zero, if I understand it correctly. That case was a bit worse -- there was no swap to swap out the data, so it was code that was removed from memory (as soon as it was file-backed and read-only) and it was paged back when instruction pointer hits the page once again (swapping some other code page out from resident set).

**Comment by darkk** [comment]
Yep, `rate(node_vmstat_pgmajfault[2m])` should show both swap and non-swap pagefault.
Thanks, I've forgotten about that :-)

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
