### ISSUE TITLE
Update piwik to matomo 3.6.0

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#225]
On analytics.ooni.io we are currently using piwik 3.0.4, while the latest version is now called matomo and is version 3.6.0.

The most important feature that we should be updating to is that allowing us to be GDPR compliant by showing annoying popover bars when visiting the site or "stripping" some user data from the logs.

I believe we actually already do some level of sanitisation of user logs, but I think it's more reliable to update to the latest version which has been looked at by people that actually understand GDPR properly. See: https://matomo.org/gdpr/

**Comment by darkk** [comment]
xref: #149
