### ISSUE TITLE
Flappy network in GH

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#227]
Impact: GH WDC VMs were unavailable for 3h:
- OONI Probe runtime &mdash; c.web-connectivity.th.ooni.io, b.collector.ooni.io, a.echo.th.ooni.io
- infra: analytics.ooni.io, shwdc.ooni.io
- dev: shark.ooni.nu, munin.ooni.io (tor th)

Some measurements could be lost due to `b.collector.ooni.io` outage.

Detection: Prometheus alert

Timeline UTC:
08 Oct 12:00 gh/ams prometheus goes offline (as observed from linode/fra) and loses sight of other VMs
08 Oct 12:06 gh/ams prometheus comes back
08 Oct 22:00 .. 09 Oct 05:00 [maintenance window](https://twitter.com/greenhost/status/1049326061178302464)
09 Oct 12:50 gh/ams prometheus goes offline (as observed from linode/fra) and loses sight of other VMs
09 Oct 12:58 gh/ams prometheus comes back
10 Oct 05:23 gh/wdc VMs disappear from gh/ams prometheus
10 Oct 08:11 gh/wdc VMs come back

What is still unclear:
- [ ] what happened

What could be done to prevent relapse and decrease impact:
- HA test-helpers
- HA collector

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
