### ISSUE TITLE
docker-build breaks with docker 18.06.1

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#229]
On macOS with the following docker version:

Docker version 18.06.1-ce, build e68fc7a

When I run the docker-build script from inside of the directory of `ooni/api` I get the following error:

```
Error response from daemon: Syntax error - can't find = in "relationship('Label',". Must be of the form: name=value
```

I believe this has something to do with the fact that it is interpreting the `git archive --format=tar` into STDIN in a different way than how it used to interpret it.

Doing some basic searching on the internet it seems like we are not the only one experiencing this problem:

 https://github.com/moby/moby/issues/28587
https://github.com/moby/moby/issues/29005
https://github.com/moby/moby/issues/31697

**Comment by darkk** [comment]
Same issue on Linux with `Docker version 18.06.1-ce, build e68fc7a`, so it's not mac-specific.

**Comment by darkk** [comment]
That's clearly a regression as there was an intention to write a test-case for raw tar file some time ago &mdash;  https://github.com/moby/moby/pull/5715#issuecomment-43275427

**Comment by hellais** [comment]
> That's clearly a regression as there was an intention to write a test-case for raw tar file some time ago

Yes I agree, yet if you look at the discussion in the tickets I linked above, it seems like they made some pretty heavy changes to their parser, which is going to make supporting this harder.

BTW while looking at this it seems like inline comments, of the style:
```
RUN echo "command 1"
    && echo "command 2"
    # This comment breaks the new parser
    && echo "command 3"
```

Will also break. I haven't run into `Dockerfile` by us that have this, but I mention it here as it also seems to be a common pitfall.

**Comment by darkk** [comment]
Yes, having a comment within multi-line shell statement always looked like a questionable practice to me. I don't remember if it breaks any of our `Dockerfile`s or not, but this specific issue is caused by bad magic: uncompressed tar file is no longer "expected" stdin input for docker-build, but compressed tar (`--format=tgz`) is. So, workaround is trivial :)
