### ISSUE TITLE
amsmetadb replica was stuck for ~4 days and crashed on sync

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#240]
Impact:
- Explorer and API showed stale data for ~4 days
- API down for 5 min
- Explorer and API down for 21h
- Explorer and API having degraded performance for ~7 days
- minor probability of metadb damage

Detection: disk exhaustion alert on hkgmetadb (postgres primary)

Timeline UTC:
- Oct 26, 17:49 @darkk starts ingestion of [simhash](https://github.com/ooni/pipeline/pull/124) values, walreceiver fetches logs at ~2…4 Mbit/s 
- Oct 29, 06:21 amsmetadb walreceiver disconnects due to timeout and reconnects to primary at ~50Mbit/s
- Oct 29, 08:21 amsmetadb walreceiver reconnects to primary and it's throttled at ~2…4 Mbit/s again 
- Nov 02, 06:00 FIRING DiskWillFillInAWeek at hkgmetadb with _"In 6d 20h. `/srv` will be full. 198.1GiB available, 28.81GiB/day growth"_
- Nov 04, 10:12 still FIRING with _"In 6d 15h 34m 24s `/srv` will be full. 157.7GiB available, 23.72GiB/day growth"_
- 12:45 as simhash calculation is expected to create some bloat, @darkk estimates amount of bloat with [a query](https://www.citusdata.com/blog/2017/10/20/monitoring-your-bloat-in-postgres/) and gets an estimate of 77GiB of bloat
- 12:47 @darkk runs `VACUUM VERBOSE ANALYZE http_control; VACUUM VERBOSE ANALYZE http_request;` to double-check bloat estimates
- 15:07 `VACUUM VERBOSE ANALYZE` completes
- 15:10 @darkk decides to run `VACUUM FULL ANALYZE http_control; VACUUM FULL ANALYZE http_request;` to reclaim 77 GiB of bloat. Tables are 112 GiB and 156 GiB, so that order is specified as only 156 GiB is available.
- 16:34 walwriter crashes with abort() due to `could not write to file "pg_xlog/xlogtemp.16": No space left on device`, primary server restarts, amsrepl reconnects, replication slowly(!) continues
- 16:30 FIRING DiskFull at hkgmetadb _"9.146GiB ~ 1% available"_
- 18:22 @darkk notices the alert and digs into the issue while `df` reports 2.9G available
- 18:40 @darkk notices that hkgmetadb has ton of unshipped WAL `257G pg_xlog` and amsmetadb has `2018-10-30/20181106T201723Z-TN-AS37693-ndt-20181030T201151Z_….json` as the last available report suggesting that transaction with 
- 18:55 @darkk restart postgresql container at amsmetadb replica to re-establish walreceiver connection
- 18:55:13 amsmetadb bounces api.ooni.io connections with `FATAL:  the database system is starting up` for a while
- 18:59:00 amsmetadb logs `database system is ready to accept read only connections`, api.ooni.io is back to life (serving a bit stale data)
- 18:55 … 19:00 WAL shipping speed goes up from ~2 Mbit/s to ~70…130 Mbit/s, situation starts to recover from 3.75d replica lag
- 19:05 DiskFull alert is resolved, ~11 GiB free
- Nov 05, 00:17 kern.log is flooded with hundreds of `xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=0 req_entries=33`, but alike messages were also observed on Oct 31 and at other VMs as well
- 00:19 amsmetadb %iowait goes from 10% of a core to ~100% of a core, write traffic to disk stops
- 00:26 amsmetadb ssh and node_exporter went down while icmp is still alive
- 08:32 @darkk notices the alert, amsmetadb is reachable via TTY but system is broken: `systemctl status ssh` and `systemctl is-system-running` fail with _timeout_, `dmesg` buffer starts with 07:xx so start of the incident is not available, `ps -A -o pid,lstart,command --forest` locks the TTY, /bin/login on tty3 hangs right on login attempt
- 09:02 as it looks like disk failure, @darkk escalates the incident to support@, meanwhile only 50 GiB of WAL logs are left unshipped at hkgmetadb
- 12:54 support@ replies saying that no disk issues are observed from dom0
- 13:14 VM is hard-rebooted and postgresql goes up with "log time" that is quite distant from crash time and enters "WAL lost" loop:
```
2018-11-05 13:14:46.062 UTC [13]:1 LOG:  database system was interrupted while in recovery at log time 2018-11-04 15:35:43 UTC
2018-11-05 13:14:46.062 UTC [13]:2 HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
2018-11-05 13:14:46.704 UTC [13]:3 LOG:  entering standby mode
2018-11-05 13:14:46.709 UTC [13]:4 LOG:  redo starts at 1BD/FE799C70
2018-11-05 13:14:49.213 UTC [13]:5 LOG:  consistent recovery state reached at 1BE/25FFE5C0
2018-11-05 13:14:49.213 UTC [1]:3 LOG:  database system is ready to accept read only connections
2018-11-05 13:14:50.410 UTC [17]:1 LOG:  started streaming WAL from primary at 1BE/25000000 on timeline 1
2018-11-05 13:14:50.410 UTC [17]:2 FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000001000001BE00000025 has already been removed
2018-11-05 13:14:51.597 UTC [18]:1 LOG:  started streaming WAL from primary at 1BE/25000000 on timeline 1
2018-11-05 13:14:51.597 UTC [18]:2 FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000001000001BE00000025 has already been removed
2018-11-05 13:14:56.604 UTC [19]:1 LOG:  started streaming WAL from primary at 1BE/25000000 on timeline 1
2018-11-05 13:14:56.604 UTC [19]:2 FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000001000001BE00000025 has already been removed
…
```
- 21:17 @darkk switches api.ooni.io to hkgmetadb &mdash; degraded speed of Explorer and API is better than complete downtime. Total amsmetadb size is 494G, 376G are newer than 2018-10-30. Total size of hkgmetadb without WAL is 542G. Given the bandwidth between amsmetadb and hkgmetadb `rsync --checksum` sounds like a better option compared to full transfer
- 21:53 @darkk `pg_drop_replication_slot('amsmetadb')` to drop extra WAL at hkgmetadb that can't be applied anyway
- 22:07 @darkk `pg_start_backup('nov05', true)` and start rsync'ing data without `pg_xlog`, `postgresql.conf`, `postgresql.pid` to amsmetadb
- Nov 06, 07:33:59 the very first `xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=19 req_entries=13` since boot at Nov 05 13:14.
- 07:34:12 amsmetadb gets ~90% of iowait at one core
- 07:38:38  amsmetadb stops receiving 100Mbit/s of network traffic, it goes down to ~200 Kbit/s, VM gets ~100% of iowait at one core (and the cpu0 is stuck in iowait till 13:12 UTC and counting) with, likely, kernel threads `[kworker/u8:0]` started at 06:56 and `[kworker/0:1]` started at 07:30 stuck in D-state. Other processes also add another core to 100% iowait statistics in 07:39…11:22 interval. 
- 11:25 incoming traffic goes down from 200 kbit/s to 5 kbit/s (and stays there till 13:12 UTC and counting)
- amsmetadb is eventually rebooted till GH rules out dom0/XEN issues
- Nov 09, 12:55 support@ declares that dom0 for amsmetadb reports hardware / memory errors, so VMs will be rebooted and that will be combined with XEN and kernel upgrades
- 13:50 email notification about pending reboot comes for 3 VMs: ssdams.infra.ooni.io, amsmetadb.ooni.nu (both down in [14:02, 14:36] window), amsapi.ooni.nu (did NOT went down)
- 16:03 support@ reports end of maintenance
- 19:03 @darkk starts `rsync --checksum` to reinitialize amsmetadb replica
- 23:42 amsmetadb starts doing disk IO quite heavily (probably, receiving checksums from rsync)
- 23:46 amsmetadb actually sees network traffic at ~100 Mbit/s
- 23:51:53 `xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=29 req_entries=4` -- first since reboot
- Nov 10, 05:49 amsmetadb stops getting network for a while and recovers at 05:59 (`rsync` is launched in retry loop)
- 05:49 amsmetadb %iowait takes off and gets to "all cores" at 06:18
- 05:50:20 the last entry in kern.log (that is pretty noisy due to max_grant_frames and iptables-LOG)
- 05:57 amsmetadb SSH stops responding with banner
- 05:50 xvda1 at amsmetadb gets stuck (according to `node_seeksample_timestamp{device="xvda1",instance="amsmetadb.ooni.nu:9100",job="node"}`), other disks are okay
- 06:18 amsmetadb stops receiving network traffic
- 08:13 amsmetadb node_exporter is no longer `up`
- 09:48 amsmetadb is not usable via TTY as well, it's force-rebooted
- 11:01 support@ _investigating further_
- 11:05 amsmetadb goes down
- 11:19 support@ _looks one of the memory dimms is faulty_
- 14:11 amsmetadb goes up
- 14:15 support@ _Your systems are up again_, faulty memory is disabled (if the correct range is selected)
- 14:23 @darkk starts rsync again
- 19:00 amsmetadb starts fetching traffic at ~30 Mbit/s
- 19:07:15 amsmetadb first `xen:grant_table: xen/grant-table: max_grant_frames reached cur=32 extra=1 limit=32 gnttab_free_count=11 req_entries=22` since reboot
- 19:56 xvda1 is stuck at amsmetadb again, last entry in kern.log
- 20:10 amsmetadb goes down again
- 20:23 amsmetadb force-stopping failed, page refresh claims the VM to be off, _Turn on_ also failed for a while. The VM went up, but control panel had hard time following it's state
- Nov 11 &mdash; disabled faulty memory did not help, node crashed again (with same `(XEN) CMCI occurred on CPU N \ (XEN) Bank X: hex[hex] at hex` errors). XEN grant table was expanded from 32 to 64 _without_ replacing DRAM module to make an experiment
- Nov 12, 19:50 `pg_create_physical_replication_slot()`, `pg_start_backup()`, `rsync`, `rsync pg_xlog` &mdash; without issues
- 21:40 `pg_stop_backup()`
- 21:45 switch API back to AMS database (a624cc7d85dc026d0ba7eca7bc7583884ceb84f6)

What went well:
- PostgreSQL handles out-of-disk situation quite gracefully

What went wrong:
- `VACUUM` card was played before looking at bare `du -x / && du -x /srv`
- XEN issue was triggered by increased load during replica sync
- PostgreSQL 9.6 replication slot can drop WAL file while `writeback` kernel thread may fail to write it to the disk

What is still unclear:
- [ ] does PostgreSQL replication slots have to be tuned in some way to delete "shipped and stored" files, and not just "shipped"
- [ ] does PostgreSQL need heartbeat UPDATE for end-to-end monitoring or does it update WALs periodically?
- [ ] does it make sense to [monitor table bloat](https://www.citusdata.com/blog/2017/10/20/monitoring-your-bloat-in-postgres/)?

What could be done to prevent relapse and decrease impact:
- `[?]` move WALs to separate partition to avoid coincidental `ENOSPC` both for storage and WAL
- [ ] roll out [postgres_exporter](https://github.com/wrouesnel/postgres_exporter) and alert on lagging replica, use [recipes](https://severalnines.com/blog/postgresql-streaming-replication-deep-dive) with textfile if postgres_exporter does not work for some reason
- [ ] upgrade to PG11 and partition large tables by hash to ease VACUUM FULL (does it improve parallel queries?)

**Comment by SuperQ** [comment]
The postgres_exporter should work very well. If you need example dashboards checkout [dashboards.gitlab.com](https://dashboards.gitlab.com). There is a `postgresql` tag.

**Comment by darkk** [comment]
@SuperQ that's good to know, thanks! I've said _"if"_ as I've seen a ticket about unsupported PG10 / PG11 and I believe that we may want to upgrade to PG11 for hash partitioning.

**Comment by darkk** [comment]
The XEN-related warning message is coming from https://github.com/torvalds/linux/commit/29d11cfd8698038b87458ba4d1329b9da81150a5
I assume, we face issue described at [Gentoo wiki](https://wiki.gentoo.org/wiki/Xen#Xen_domU_hanging_with_kernel_4.3.2B) and [Debian bug tracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880554) suggesting to bump `gnttab_max_frames` at dom0.

**Comment by darkk** [comment]
I've switched API back to amsmetadb and resumed simhash ingestion.

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
