### ISSUE TITLE
WDC migration and re-numbering

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#241]
GH / WDC migrates to Miami.
Hardware will be physically moved, IP addresses will be re-numbered.
So, everything that is there, should be killed, frozen or moved.
This migration will happen in the week 26 Nov ... 02 Dec.

- [x] munin.ooni.io
- [x] shwdc.ooni.io
- [x] shark.ooni.nu
- [x] a.echo.th.ooni.io
- [x] c.web-connectivity.th.ooni.io
- [x] b.collector.ooni.io
- [x] analytics.ooni.io

**Comment by darkk** [comment]
- munin &mdash; gone, disk image will be removed in a while, Tor TH will be re-deployed preserving keys
- shwdc &mdash; gone, replaced with another bastion host, disk image is deleted as it had no files in home directories

**Comment by darkk** [comment]
- shark.ooni.nu &mdash; VM deleted, but disk image is kept for a while. I believe, this VM was used for one-off testing and it has not seen any shell logins since Oct 16, so I'm unsure if allocated resources are still needed. @hellais, please tell, if you still need the data stored there.

**Comment by darkk** [comment]
## analytics.ooni.io

I believe, it can go down for a week and come back online after migration. Moreover, it uses only 1.2 GB of RAM (470 MB without disk cache) out of 6 GB allocated.

**Comment by darkk** [comment]
# c.web-connectivity.th.ooni.io & b.collector.ooni.io

I decided to avoid migration of these services, so I just disabled corresponding collector and test-helper at the bouncer.

**Comment by darkk** [comment]
`b.collector.ooni.io` is hardcoded, so bouncer reply is probably not respected (anyway, traffic did not go away after bouncer configuration change) -- https://github.com/measurement-kit/measurement-kit/blob/v0.9.0-beta/src/libmeasurement_kit/ooni/collector_client.hpp#L18-L19
Seems, endpoint should be migrated somewhere.

**Comment by darkk** [comment]
UPD from @bassosimone: the collector is indeed hardcoded, but the hardcoded value is used as a fallback when bouncer does not reply. It explains both the existence of traffic and very low amount of measurements hitting `b.collector.ooni.io` endpoint.

**Comment by darkk** [comment]
Unfortunately `c.web-connectivity.th.ooni.io` still gets some traffic to `y3zq5fwelrzkkv3s.onion`. The source is unclear.

**Comment by darkk** [comment]
I've moved y3zq5fwelrzkkv3s.onion frontend to `b.web-connectivity.th.ooni.io`, seems, it's working.
I hope, that's enough for the clients that had that onion address hardcoded to survive.

**Comment by darkk** [comment]
FTR, number of test-helpers from 2018-11-20 bucket:
```
$ ( for f in *.tar.lz4; do tar -I lz4 -xf - --to-stdout < $f; done; for f in *.json.lz4; do lz4cat <$f; done ) | jq -c .test_helpers | sort | uniq -c
  55748 {}
    360 {"backend":"37.218.247.110"}
    387 {"backend":"http://37.218.247.95:80"}
      1 {"backend":"http://a.echo.th.ooni.io"}
     20 {"backend":{"type":"https","address":"https://b.web-connectivity.th.ooni.io"}}
   9268 {"backend":{"type":"https","address":"https://b.web-connectivity.th.ooni.io:443"}}
   9767 {"backend":{"type":"https","address":"https://c.web-connectivity.th.ooni.io:443"}}
 235919 {"backend":{"type":"onion","address":"httpo://y3zq5fwelrzkkv3s.onion"}}
      1 null
```

**Comment by darkk** [comment]
- [ ] a.collector.ooni.io handles traffic "correctly", but the report files are for some reason not moved from `archive` to `renamed` directory.

**Comment by hellais** [comment]
> a.collector.ooni.io handles traffic "correctly", but the report files are for some reason not moved from archive to renamed directory

It seems to not be working as expected, because the `daily-task` is not running properly due to:

```
Traceback (most recent call last):
  File "/data/collector/bin/archive-to-renamed.py", line 5, in <module>
    import yaml
ImportError: No module named yaml
```

**Comment by darkk** [comment]
Does it mean, that it may actually drop some ancient traffic in yaml format as well?...

**Comment by hellais** [comment]
> Does it mean, that it may actually drop some ancient traffic in yaml format as well?...

That should not be a problem, because the actual collector code is run inside of a docker container. The daily cronjob is scheduled to run outside of docker.

I am re-running the playbook with the addition of an apt-get install of `python-yaml`.

**Comment by darkk** [comment]
> The daily cronjob is scheduled to run outside of docker

Sidenote: the slightly more robust way to handle that may be to schedule `docker exec` or `docker run` as a cronjob (or as a systemd timer).

Here is the checklist of the second leg of the migration:

- [ ] restore shark disk image somewhere
- [ ] restore onion keys from a.echo.th.ooni.io to check if it gets traffic
- [ ] keep a.echo.th.ooni.io pointed to c.echo.th.ooni.io
- [ ] check `b.collector.ooni.io` domain name, it should point to miacollector.ooni.nu
- [ ] clean-up 103.104.244.110 (aka a.collector.ooni.io) from `b.collector.ooni.io` domain name and such
- [ ] ensure that migrated `c.web-connectivity.th.ooni.io` gets traffic for `y3zq5fwelrzkkv3s.onion`
- [ ] clean `y3zq5fwelrzkkv3s.onion` from `b.web-connectivity.th.ooni.io`
- [ ] check if `analytics.ooni.io` points to correct VM
- [ ] update airflow WRT have_collector

**Comment by darkk** [comment]
### update bouncer configuration

[Done](https://github.com/ooni/sysadmin/pull/247/commits/c422d3520d68ba00ab651eb8b5c59b6ea1a9913a),

Other pending sub-tasks in this ticket wait for the mail chain with GH to converge.

**Comment by gabelula** [comment]
It seems that this one was done. Can we close this issue?

**Comment by hellais** [comment]
> restore shark disk image somewhere

I am OK with the shark disk image not being restored at this point as I now have another build system for linux.

**Comment by gabelula** [comment]
Can we close it now? Do we need @hellais to review this?

**Comment by gabelula** [comment]
@darkk  There are a few items in your list in this issue that were not ticket off. Were those done?

**Comment by darkk** [comment]
Yep.
No traffic was noticed for onion counterpart of a.echo.th.ooni.io and it's not listed in bouncer config, so it's gone.
Tor TH in MIA was rolled out as part of 69892e3327a88cc1a3dbf7af0e53433e2c575769

**Comment by hellais** [comment]
This looks good to me. Moving it to the done column.
