### ISSUE TITLE
Open recursive resolver at ooni-zoo.infra.ooni.io used for amplification attack

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#248]
Impact: unclear

Detection: _[Ticket#10628841] [Abuse] DDoS Attack from your 37.218.240.13_

Timeline UTC:
20 Nov 18:04 `Date` of the email _From: Konstantine Gardner <abuse@altvpn.com>, To: abuse@greenhost.nl_
26 Nov 16:17 Ticket#10628841 arrives to admin@
26 Nov 16:28 @darkk acknowledges the ticket but is AFK
27 Nov 10:40 investigation started
27 Nov 11:08 `bind` is stopped at the VM

What went wrong:

* the open resolver at `ooni-zoo.infra.ooni.io` was used to plot DDoS attack as DNS-amplifier with x40...x50 factor using query `ANY USADF.GOV.`
* peak rate of outgoing traffic for that VM during last two weeks was ~25 Mbit/s, so it did not trigger high-bandwidth alert

What is still unclear:

* [x] what's the history of `bind` daemon at that host? @hellais @bassosimone @anadahz , does anyone remember?
* [x] [%7Bdevice%3D%22eth0%22%2Cinstance%3D%22bouncer.infra.ooni.nu%3A9100%22%2Cjob%3D%22node%22%7D%5B1m%5D bouncer.infra.ooni.nu ](https://mon.ooni.nu/prometheus/graph?g0.range_input=1d&amp;g0.expr=irate(node_network_transmit_bytes) %2F irate(node_network_receive_bytes%5B1m%5D)&g0.tab=0) also has high TX/RX traffic ratio, is it ok?

What could be done to prevent relapse and decrease impact:

* [ ] alert on high (> 2?) non-tcp TX/RX traffic ratio

**Comment by darkk** [comment]
Seems, the bouncer.infra.ooni.nu is okay. The TX/RX ratio is coming from TCP (monitoring an idle host).

**Comment by anadahz** [comment]
> what's the history of bind daemon at that host? @hellais @bassosimone @anadahz , does anyone remember?

IIRC this was a resolver made for a test related to MK.

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
