### ISSUE TITLE
a.collector was not running properly

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#250]
As part of https://github.com/ooni/sysadmin/issues/241 we noticed that a.collector had not been migrated properly as part of [May incident documented in #183](https://github.com/ooni/sysadmin/issues/183#issuecomment-386816929).

Namely the daily cronjob was not running properly and not moving files from `archived` to `renamed`.

The problems with it were:

1. python-yaml was missing so it was failing on the import
2. the `archive-to-renamed.py` script was referencing some paths that were specific to the c.collector installation and were not codified in the playbook (`RENAMED_LOG_DIR`)
3. The collector user did not have appropriate permissions to change the owner of the renamed directory

Impact: ingestion of some of the measurements was slightly delayed.

This collector was not receiving any measurements and the latest measurement on the box was dated 2018-11-26.

This probably could have been prevented by:

* Testing the full workflow of the collector before considering it migrated (before the above incident this collector was receiving zero traffic)

**Comment by darkk** [comment]
> The collector user did not have appropriate permissions to change the owner of the renamed directory

Following permissions would prevent `sync-user` from deleting the measurements after `rsync`:

```
  File: ‘/data/collector/renamed/’
Access: (0755/drwxr-xr-x)  Uid: ( 8001/collector)   Gid: ( 8001/collector)
```

I assume, it may lead to duplicate measurement accumulating as rsync will be retried at least daily.

**Comment by hellais** [comment]
> Following permissions would prevent sync-user from deleting the measurements after rsync:

Is that the case even if the files themselves are world writable?

**Comment by hellais** [comment]
The above should be fixed in: https://github.com/ooni/sysadmin/pull/249/commits/e86d105929a9d01221dfb7adcd7221caeba63cfd

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
