### ISSUE TITLE
OpenDNS resolver unreachability triggers alert storm

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#252]
Impact: alert storm (~250 emails), anything else?

Detection: alert storm :-)

Timeline UTC (05 Dec):
02:06 ICMP and SSH probe mass-failure at `prometheus.infra.ooni.io`: `up=0` so the result can't be scraped from `blackbox_exporter` at all, `scrape_duration_seconds` becomes 10.000s for corresponding jobs (usual `scrape_duration_seconds` for failing ICMP and SSH probes is ~4.502s in this setup)
02:12 first non-zero `alertmanager_notifications_failed_total` from prometheus.infra.ooni.io:9093
02:14 last `job="node"` failure  at prometheus.infra.ooni.io, the failures of `job="node"` were spread across 8 minutes
02:16 `alertmanager` complains a lot about name i/o timeouts during lookup
02:21 ICMP, SSH and `job="node"` mass-recovery at `prometheus.infra.ooni.io`, `probe_dns_lookup_time_seconds`, last non-zero `alertmanager_notifications_failed_total`

What went well:
- thanks to cross-monitoring with another independent instance, there is some visibility regarding the incident, namely `irate(net_conntrack_dialer_conn_failed_total[1m]) > 0` confirms that DNS is the issue

What went wrong:
- prometheus.infra.ooni.io was configured with OpenDNS resolvers: `208.67.222.222`, `208.67.220.222`. As expected (after #159), both go down at the same time.
- prometheus.infra.ooni.io was unable to scrape it's own node_exporter statistics (also expected)

What is still unclear:
- [ ] does `blackbox_exporter` respect scrape timeout while doing DNS queries? It should fail-fast to stay "up", but it fails completely.
- [x] should `blackbox_exporter` and `prometheus` cache DNS names for TTL? They're going to use same name over and over again...

What could be done to prevent relapse and decrease impact:
- [ ] use two _really_ different nameservers in `resolv.conf`

**Comment by darkk** [comment]
Local CoreDNS-based DNS cache was added as a part of public *.onion endpoints monitoring within #239

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
