### ISSUE TITLE
Drop third collector VM

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#257]
I and @hellais  are in agreement to:
- drop the third collector (the one in HKG), so only two are left
- move it's DNS name to one of the existing ones (probably, AMS)
- move it's onion keys to tor daemon at the host of the collectors & add separate logging at nginx level, to know if there is traffic arriving there or not

...as soon as the third collector does not provide any value (serves just a tiny fraction of traffic) and does not have corresponding "third" test-helpers.

Pre-req is #241

**Comment by hellais** [comment]
This is done as part of oonification of services.
