### ISSUE TITLE
Write documentation for docker-trampoline

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#268]
It would be useful to have better docs written for the `docker-trampoline` script.

Things that should be documented in it are:

* [ ] What is the purpose of this script (ex. it's to provide some extra level of security for running things inside of docker)
* [x] What the commands that currently exist in there are doing
* [x] How new commands can be added to the script
* [ ] How the pattern `set -- /bin/bash -c 'XXX'` works
* [ ] What the variables `script`, `bucket`, `isofrom`, `isotill` mean exactly and how they are being validating in the script
* [ ] What is the best process for debugging failures in this script given that the airflow stacktrace does not give info on that

**Comment by darkk** [comment]
I've added some text on the script purpose to the header, I think the text kinda answers most of the questions, but I'd expand some ellipses.

> What the commands that currently exist

Those are the commands those are executed from [`airflow-dags`](https://github.com/ooni/sysadmin/tree/master/ansible/roles/airflow/files/airflow-dags). `shovel_jump.sh` lists commands as `task.task_id`, so the command is actually a `task_id` of a Task in an airflow DAG.

> How new commands can be added to the script

I think, this commit serves as a good minimal example: https://github.com/ooni/sysadmin/commit/324fdd240bff9374fe7e1b880daadb81c792adf9

> How the pattern set -- /bin/bash -c 'XXX' works

There is nothing fancy here, `man bash` describes that.
`set -- foo bar` replaces `$@` of the current shell with `foo bar`.
It's used with a fall-through after `case / esac` and pass args to `openobservatory/pipeline-shovel:20190426-065cccdf` as `"$@"`.
It may deserve some refactoring to make it less ugly, but IMHO shell scripts are always a bit ugly and copy-pastish :)

> What the variables script, bucket, isofrom, isotill mean exactly

Their meaning is defined at the point of invocation. The validation is a weak regexp and it there mostly to prevent typos.

> What is the best process for debugging failures in this script

The process is the same as for any other shell script: `set -o xtrace` and read the logs when/if the reason of failure is not obvious on its own.

**Comment by hellais** [comment]
I think we have enough information on this. Closing.
