### ISSUE TITLE
Half of 2019-01-05 bucket stalled for 10d

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#270]
Impact: 3912 reports (half of the bucket 2019-01-05) were processed with 10d delay

Detection: monitoring alert

Timeline UTC:
Jan 06 00:20 `collector_sensor_miacollector` Marking task as FAILED. (as miacollector.ooni.nu is not responding to pings for a while)
Jan 06 00:21 `rsync_collector_miacollector` starts rsync and fails, miacollector.ooni.nu is temporary unreachable
Jan 06 00:26 `rsync_collector_miacollector` does the 2nd attempt of rsync, rc=0, no files are transferred (as they're not renamed yet)
Jan 06 00:32 `collector_sensor_c.collector` Success criteria met. Exiting.
Jan 06 00:32 `rsync_collector_c.collector` starts rsync
Jan 06 00:48 `rsync_collector_c.collectorr` completes rsync, rc=0
Jan 06 01:01 `collector_sensor_hkgcollectora` AirflowSensorTimeout: Snap. Time is OUT.
Jan 06 01:01 `rsync_collector_hkgcollectora` does rsync of ~empty spool, rc=0
Jan 06 01:04 `reports_raw_merge` is done, rc=0
Jan 06 01:06 `hist_canning/reports_raw_sensor` sees a token from `reports_raw_merge` and starts bucket processing
Jan 06 01:20 `FIRING` Last `collector_sensor_miacollector` failure 1d 1h ago.
Jan 06 02:27 `hist_canning` DAG is done, `reports-raw` is cleaned up
Jan 06 20:57 @hellais _The failure backtrace of `miacollector` [is not super useful](https://openobservatory.slack.com/archives/C38EJ0CET/p1546808262017400)_ 
Sidenote: the backtrace [follows failed `ping` command](http://127.0.0.1:8080/admin/airflow/log?task_id=collector_sensor_miacollector&dag_id=fetcher&execution_date=2019-01-05T00:00:00) showing that miacollector.ooni.nu is not responding to pings: ping failed and rc=1 stops script execution.
Jan 06 21:01 `collector_sensor_miacollector` Starting attempt 1 of 1, 3912 new reports
Jan 06 21:02 @hellais _I am just going to be clear the task state and see if it recovers that way_
Jan 06 21:03 `rsync_collector_miacollector` Starting attempt 1 of 1
Jan 06 21:17 `rsync_collector_miacollector` rc=0, 3912 new reports copied
Jan 06 21:18 `reports_raw_merge` is restarted (while previous task instance was successful), renames some files and fails with `/reports-raw-shals/2019-01-05: cannot overwrite existing file`
Jan 06 21:34 @hellais _Hum, now the `reports_raw_merge` task is failing due to `2019-01-05: /reports-raw-shals/2019-01-05: cannot overwrite existing file`_ 
Jan 06 21:40 @hellais _Maybe actually re-running the sync task was the wrong thing to do. I am going to, as a safety measure, I am going to `cp -R /data/ooni/private/reports-raw/2019-01-05/ /home/art/backup-2019-01-05`_
Jan 06 22:31 @darkk _Buckets should be independent, so it _should_ recover, but the previous bucket will be left "unprocessed", but buckets are not completely independent as spool is shared across buckets_
Jan 06 22:37 @darkk _The spool is empty, it means that the next tick will be independent from this one (and may succeed)_
Jan 16 11:00 @darkk moves data that was erratically renamed to `/data/ooni/private/reports-raw/2019-01-05/*` back to the spool `/data/ooni/private/spool/miacollector.ooni.nu/`, the data should be ingested on the next pipeline tick
Jan 16 11:30 the incident is published

What went wrong:
- the issue looked like temporary glitch at first, so it was de-prioritized, so the data was stuck for 10d instead of 1d due to holidays and postponed incident response
- clearing the state of successful `reports_raw_merge` task instance renamed some files and made data stuck for 10d (till manual intervention) instead of 1d (till auto-self-healing)

What could be done to prevent relapse and decrease impact:
- [ ] prevent `reports_raw_merge` re-run in case of human mistake: if the bucket is frozen (list of report files is converted to SHA1 checksum), it's frozen forever
- [ ] mark directories read-only (or replace them with sentinel files) after cleanup task to prevent human mistakes

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343
