### ISSUE TITLE
 GH hosts missing from inventory

### ISSUE THREAD

**Issue by darkk** [ooni/sysadmin#276]
@hellais @bassosimone what's the destiny of the following hosts? Should they be kept? Should they be dropped?

- [ ] `{"v4":"103.104.244.21","name":"testing","dc":"Hong Kong"}`
- [ ] `{"v4":"37.218.241.4","name":"cu-testing-s1","dc":"US East (Miami)"}`
- [ ] `{"v4":"37.218.242.89","name":"cu-testing-s2","dc":"Amsterdam"}`

They were created some time ago, but they're not tracked in `inventory`, not monitored and so on.

**Comment by bassosimone** [comment]
@darkk I do not know anything about them so I’d say deploy the napalm, then maybe we can go windsurfing :)

**Comment by hellais** [comment]
cu-testing-* where some boxes I setup to do some experiments, but didn't get too far with the experimentation.

testing (according to my ~/.ssh/config) is marked as `dns.ooni.io`, but I don't recall what it was for.

I suggest dropping all three of these hosts and if we need them they can be recreated.

**Comment by darkk** [comment]
Okay. I stopped them and will drop tomorrow. `testing` was unable to boot properly anyway, it's console was showing busybox.
