### ISSUE TITLE
Update ooni run playbook to use docker

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#278]
Currently the OONI Run playbook is not so reliable and in the last update I did to it I had to manually update it.

We should probably use the same docker based strategy we use for other node.js based tools for this as well.

**Comment by darkk** [comment]
Isn't that a duplicate of https://github.com/ooni/run/issues/14 ?

**Comment by hellais** [comment]
This happened again while looking into: https://github.com/ooni/run/issues/23

**Comment by hellais** [comment]
This is done.
