### ISSUE TITLE
Update all vms on jessie to buster

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#287]
Due to https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html and the resulting breakage with letsencrypt by means of jessie-backports not working anymore, I think it would be wise to upgrade all VMs that are currently on jessie to stretch.

This will likely take a while, but I would prioritise those which are using the letsencrypt role.

**Comment by darkk** [comment]
Scary stuff: `b.echo.th.ooni.io` is `wheezy`.

**Comment by hellais** [comment]
This has been done as part of https://github.com/ooni/sysadmin/issues/356. Some hosts are still missing (like databases), but they each have their own issue to track them.
