### ISSUE TITLE
Create a periodic database dump of the metadb

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#309]
As discussed in https://github.com/ooni/sysadmin/issues/272#issuecomment-487605535 we should periodically create a new full DB dump that we base the WAL increments from.

This may either be as a airflow task or a cronjob.

**Comment by darkk** [comment]
If that follows a pattern of cronjob instead of airflow task, I'd suggest to hook it's status to Pushgateway monitoring (like it's done for hellais-nas backup and WAL shipment that is a cronjob-style script controlled by postgres). Otherwise there is a risk of a silent cronjob rot.
