### ISSUE TITLE
2019-06-21 pipeline stall

### ISSUE THREAD

**Issue by bassosimone** [ooni/sysadmin#327]
This afternoon I logged into Slack and saw the following alerts:

```
AlertManager [12:57 UTC]
[FIRING] 1 DAG `hist_canning` failures last week
Last `hist_canning` failure 2d 13h ago. Yours airflow.

[FIRING] 1 task `reports_raw_sensor` failures last week
Last `reports_raw_sensor` failure 2d 13h ago.
```

Therefore, at 14:40 UTC I logged into the Airflow control panel. The root cause of the failure seemed to be that the `rsync_collector_hkgcollectora` task failed like:

```
*** Log file isn't local.
*** Fetching here: http://:8793/log/fetcher/rsync_collector_hkgcollectora/2019-06-21T00:00:00
*** Failed to fetch log file from worker.
[...]
```

This log is weird in that the hostname is missing on the URL (for reference, this is what happened instead on 2019-06-22):

```
*** Log file isn't local.
*** Fetching here: http://af-worker:8793/log/fetcher/rsync_collector_hkgcollectora/2019-06-22T00:00:00
[snip]
```

To remediate that, at 15:00 UTC I forced the `rsync_collector_hkgcollectora` task to run again, and this time it produced the following logs:

```
*** Log file isn't local.
*** Fetching here: http://af-worker:8793/log/fetcher/rsync_collector_hkgcollectora/2019-06-21T00:00:00

[...]

[2019-06-23 15:02:31,028] {jobs.py:2083} INFO - Task exited with return code 0
```

This made the `fetcher` green again. After that, at 15:10 UTC I checked the logs of the `hist_canning` DAG; `reports_raw_sensor` failed like this:

```
*** Log file isn't local.
*** Fetching here: http://af-worker:8793/log/hist_canning/reports_raw_sensor/2019-06-21T00:00:00

[...]
[2019-06-22 00:00:10,651] {base_task_runner.py:95} INFO - Subtask: sha256sum: /data/ooni/private/reports-raw-shals/2019-06-21: No such file or directory
```

However, at 15:11 UTC the missing file was clearly present:

```
root@datacollector:/data# ls -lh ooni/private/reports-raw-shals/2019-06-21 
-rw-r--r-- 1 benchmark benchmark 68 Jun 23 15:02 ooni/private/reports-raw-shals/2019-06-21
```

and of course the reason is that running again the `fetcher` caused that file to appear. So, to continue fixing, at 15:15 UTC I cleared recursively the `reports_raw_sensor` task of the 2019-06-21 bucket. This caused reprocessing and ultimately:

```
AlertManager [15:17 UTC]
[RESOLVED] 1 DAG `hist_canning` failures last week
Last `hist_canning` failure 2d 15h ago. Yours airflow.

AlertManagerAPP [15:19 UTC]
[RESOLVED] 1 task `reports_raw_sensor` failures last week
Last `reports_raw_sensor` failure 2d 15h ago.
```

## What went well

Alerting was useful. Knowledge transfer was good enough to allow me to restart the failed DAGs and make sure the pipeline was in okay state.

## What went wrong

It's not obvious the reason why the URL passed to the task was malformed.

## What is still unclear

Where did 2019-06-21 data go (I'm still trying to understand.)

**Comment by bassosimone** [comment]
As an additional comment, I'm not sure I quoted the right excerpt from the logs of the failed `reports_raw_sensor` task. I probably missed the real error.

As for where are the 2019-06-21 data, I've noticed that `canned/2019-06-22/index.json.gz` contains indeed file names referencing the 2019-06-21 date. Therefore, I believe it is reasonable to assume that the 2019-06-21 data have been processed by the 2019-06-22 DAG. Conversationally, I have been told in the past by @hellais and @darkk that this is expected behaviour.

**Comment by darkk** [comment]
> Therefore, at 14:40 UTC I logged into the Airflow control panel. The root
> cause of the failure seemed to be that the rsync_collector_hkgcollectora
> task failed like:
>
> *** Log file isn't local.
> *** Fetching here: http://:8793/log/fetcher/rsync_collector_hkgcollectora/2019-06-21T00:00:00
> *** Failed to fetch log file from worker.
> [...]
>
> I consider it as an unlikely root cause on its own. I consider lack of
hostname in this URL some sort of Airflow bug. I say so as I've previously
seen the log file for the corresponding task instance being correctly
written to the disk to the corresponding directory under /srv in an alike
case.

I would suggest to inspect that file, maybe it will give a hint about the
root cause of the issue  itself and/or the cause triggering the
hypothetical airflow bug.

**Comment by bassosimone** [comment]
@darkk my understanding is that running the task cleared the previous logs. If that's not the case, then I'm clearly failing to find previous run's logs in the AirFlow UI. If it's confirmed that I caused the logs to overwrite, then that's clearly some serious doofus :(.

**Comment by darkk** [comment]
Logs were appended, but they were still unavailable via web UI in previous
cases. The only way to access the logs in the previous cases was to look at
the actual log files on data collector FS.

But maybe there is something different in this case. Anyway, I'm just
sharing my previous observations on `http://:port/...` :-)

**Comment by bassosimone** [comment]
I believe I don't have time to spend to further investigate the cause of the stall. I think it's fine to sometimes have pipeline stalls by transient errors. I'm going to close this.
