### ISSUE TITLE
Create VM to host testing collector

### ISSUE THREAD

**Issue by bassosimone** [ooni/sysadmin#330]
The plan at https://github.com/ooni/probe/issues/863 calls for @bassosimone creating a new VM to host the testing collector. This is the place to deploy single measurement submission both using the old and afterwards the new collector.

Although this VM should have a domain name assigned, it should probably not be maintained for a long time period, but rather it should be regarded as an experiment.

Deploying this new VM is also an opportunity to understand how to adapt our existing Ansible scripts to use the latest version of Debian and, generally, it is an opportunity for @bassosimone to get more experience regarding redeploying our infrastructure.

**Comment by hellais** [comment]
This is done.

You can now use `ps-test.ooni.io` as your testing collector :)
