### ISSUE TITLE
Slacktopus is not transmitting messages to IRC endpoint

### ISSUE THREAD

**Issue by anadahz** [ooni/sysadmin#332]
Slacktopus (bridge) IRC user is not transmitting Slack message to the IRC endpoint of ooni channel.

**Comment by hellais** [comment]
This has been fixed.

Impact:

Users on IRC were not receiving messages from Slack. Slack users were still receiving messages from IRC.

Timeline of the incident:

2019-07-07 anadahz APP [15:26]
OK it's been some time that slacktopus5 doesn't transmit Slack messages to IRC.

hellais logs into `slack.openobservatory.org` and restarts the docker container of the bridge.

2019-07-08 hellais APP [12:40]
ok the bridge is back up

What we should do in the future:

* [ ] Setup monitoring to ensure the bridge is up and working

**Comment by hellais** [comment]
https://github.com/ooni/backend/issues/343

**Comment by hellais** [comment]
Migrated to: https://github.com/ooni/backend/issues/344
