### ISSUE TITLE
Drop brie.darkk.net.ru from monitoring

### ISSUE THREAD

**Issue by bassosimone** [ooni/sysadmin#415]

**Comment by darkk** [comment]
FTR, I've dropped `prometheus.infra.ooni.io` monitoring from `brie.darkk.net.ru` host as well.
I'd also suggest to drop following IP addresses from the [_"Email whitelist"_](https://support.google.com/a/answer/60751) for `@openobservatory.org` Google Apps domain:
- 139.162.172.21
- 2a01:7e01::f03c:91ff:fe0a:f4eb
- 2a01:7e01:e001:7c:494c:6f76:6552:4b4e

**Comment by bassosimone** [comment]
Thanks, @darkk!
