### ISSUE TITLE
Metadb Replica Access - postgres user

### ISSUE THREAD

**Issue by lukaskawerau** [ooni/sysadmin#431]
I now have a running replica of the Metadb, but I'm still struggling to log in to it.
When I use DBeaver to try and connect to the DB, I get `The server requested password-based authentication, but no password was provided.` when I set `postgres` as the user.  
Since it's a replica, I also can't create a new user and give them a new password.

How do I access the data in the DB? Would super appreciate any help!

**Comment by hellais** [comment]
Hi thanks for reaching out and sorry for the late follow up here (we use https://github.com/ooni/backend/issues for reporting issues pertaining to backend infrastructure).

I believe you eventually got the answer you were looking for from the OONI slack, if you still need some help feel free to open another issue in ooni/backend or reach out to us on slack!
