### ISSUE TITLE
Cleanup obsolete/discontinued OONI infrastructure 

### ISSUE THREAD

**Issue by anadahz** [ooni/sysadmin#48]
Let's remove the obsolete infrastructure from this [page](https://github.com/TheTorProject/ooni-sysadmin#ooni-infrastructure-overview).

**Comment by anadahz** [comment]
ooni-deb 	debian repository, collector
marcello 	development/playground
ooni-tpo-collector 	backup collector
@hellais are these active?

**Comment by hellais** [comment]
* ooni-deb debian repository, collector

Still online, but has not been used since many months. I think it should either be repurposed for something else or deprecated.

* marcello development/playground

Still online, but has not been used in many months. Also should either be deprecated or decommissioned.

* ooni-tpo-collector backup collector

OFFLINE.

* probes

OFFLINE

**Comment by hellais** [comment]
Is anything else needed on this ticket?

**Comment by hellais** [comment]
Bump

**Comment by hellais** [comment]
Is this done?

**Comment by hellais** [comment]
Are there any updates on this?

**Comment by darkk** [comment]
Does the ticket include resource de-allocation? Who is accounting resources? :-)

**Comment by hellais** [comment]
> Does the ticket include resource de-allocation?

Yeah we should take this as an opportunity to also do an inventory of all the current resources and ensure we are using them and if not de-allocate them.

I checked our aws account and I currently see that we are running a series of services that I don't think we need to be running:

* ooni-api-1 (I believe now the explorer is run on greenhost so we can kill this, right?)
* ooni-bridge-reachability-collector (I am not sure what this is for, @anadahz do you remember?)
* human (also unsure what this is for)

**Comment by darkk** [comment]
I believe, this can be closed (TTL exceeded).
I don't see any references for those pieces of infra, if they're still up and running, they should be added in `inventory` and that has not happened for a year, so they probably are not.
