### ISSUE TITLE
Slack bridge is not transmitting messages to IRC channel

### ISSUE THREAD

**Issue by anadahz** [ooni/sysadmin#481]
The Slack bridge seems to not transmit message from Slack to IRC but IRC messages are transmitted to Slack channel.

Last seen messages on IRC (from Slack): 31 May 2021

**Comment by hellais** [comment]
It looks like currently there is an issue with the communication between IRC and slack. Apparently this is a known problem of the library we use: https://github.com/ekmartin/slack-irc/issues/269.

Apparently there is a fix for it, but it hasn't been merged into upstream: https://github.com/ekmartin/slack-irc/pull/271.

I guess we could workaround this by updating [our Dockerfile](https://github.com/ooni/sysadmin/tree/master/docker/slack-irc) to use the version with this patch.

Alternatively we could look into some other library which does the same thing but is actively maintained.

**Comment by hellais** [comment]
I ended up making a fork of slack-irc on our OONI repo: https://github.com/ooni/slack-irc and updated our dockerfile to use that fork.

It seems to have fixed the issue we have been encountering, so I guess we can consider this issue resolved.
