### ISSUE TITLE
Cleanup dead code from this repository

### ISSUE THREAD

**Issue by hellais** [ooni/sysadmin#94]
This repository contains a bunch of dead code that is no longer needed/used/working.

I was thinking that this was sort of implied by what would be done in https://github.com/TheTorProject/ooni-sysadmin/issues/48, but I realise now that maybe the scope of that ticket is too narrow, so I will create a ticket for this.

Things that we should evaluate if they should still stay are are:

* [x] `ooni-sysadmin-ng/`
* [ ] `settings/`
* [ ] `ansible/server_migration/`
* [x] `tasks.py`
* [x] `invoke.yaml.example`

Potentially many more.

It would be good to go through all this repo and prune out all the stuff that is obsolete and no longer needed

**Comment by darkk** [comment]
I think, it's done during #217.
